[versions]

# libraries
markdown = "0.4.1"

# plugins
dokka = "1.8.20"
gradlePluginPublish = "1.2.0"
gradleChangelogPlugin = "2.1.0"

[libraries]
markdown = { group = "org.jetbrains", name = "markdown", version.ref = "markdown" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
changelog = { id = "org.jetbrains.changelog", version.ref = "gradleChangelogPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
