[versions]

# libraries
markdown = "0.7.3"

# plugins
dokka = "1.9.20"

gradlePluginPublish = "1.3.0"
gradleChangelogPlugin = "2.2.1"


[libraries]
markdown = { group = "org.jetbrains", name = "markdown", version.ref = "markdown" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
changelog = { id = "org.jetbrains.changelog", version.ref = "gradleChangelogPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
bcv = "org.jetbrains.kotlinx.binary-compatibility-validator:0.16.3"
