[versions]
# libraries
markdown = "0.7.3"
junit = "4.13.2"

# plugins
dokka = "2.1.0"
bcv = "0.18.1"
gradlePluginPublish = "2.0.0"
gradleChangelogPlugin = "2.4.0"

[libraries]
markdown = { group = "org.jetbrains", name = "markdown", version.ref = "markdown" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePluginPublish" }
changelog = { id = "org.jetbrains.changelog", version.ref = "gradleChangelogPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
bcv = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "bcv" }
