name: Test Report
run-name: >
  Test Report for ${{ github.event.workflow.name }}
  #${{ github.event.workflow_run.run_number }}:
  ${{ github.event.workflow_run.display_title }}
on:
  workflow_run:
    workflows: [Build]
    types: [completed]

permissions:
  checks: write

jobs:
  report:
    name: Test Report
    runs-on: ubuntu-latest

    steps:

      - name: Test Report
        uses: dorny/test-reporter@v2
        with:
          artifact: /test-results-([^-]*)-(.*)/
          name: "Unit Tests Report: Gradle $1 @ $2"
          path: "test-results/*/TEST-*.xml"
          reporter: java-junit
